# Generated by Django 5.1.7 on 2026-07-31 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(max_length=20)),
                ('indicator_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('source', models.CharField(default='FRED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=20)),
                ('source_type', models.CharField(choices=[('10K', '10-K Filing'), ('10Q', '10-Q Filing'), ('EARNINGS', 'Earnings Call'), ('NEWS', 'News Article'), ('CUSTOM', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('chromadb_collection', models.CharField(max_length=100)),
                ('chunk_count', models.IntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('model_type', models.CharField(choices=[('LSTM', 'LSTM'), ('GRU', 'GRU'), ('FNN', 'FNN'), ('XGBOOST', 'XGBoost'), ('CATBOOST', 'CatBoost')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=20)),
                ('stock_name', models.CharField(blank=True, max_length=200)),
                ('time_horizon', models.CharField(choices=[('SHORT', 'Short-term'), ('LONG', 'Long-term')], max_length=10)),
                ('investment_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=20)),
                ('fundamental_score', models.FloatField(blank=True, null=True)),
                ('quant_score', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('fundamental_data', models.JSONField(blank=True, default=dict)),
                ('quant_data', models.JSONField(blank=True, default=dict)),
                ('sentiment_data', models.JSONField(blank=True, default=dict)),
                ('shap_values', models.JSONField(blank=True, default=dict)),
                ('top_factors', models.JSONField(blank=True, default=list)),
                ('nn_model_used', models.CharField(blank=True, max_length=20)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('prediction_horizon_days', models.IntegerField(blank=True, null=True)),
                ('portfolio_suggestion', models.JSONField(blank=True, default=dict)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('reward_signal', models.FloatField(blank=True, null=True)),
                ('actual_outcome', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='research.stockanalysis')),
            ],
        ),
    ]
