# Generated by Django 5.1.7 on 2026-07-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenttask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='investmentfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='macroindicator',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='ragdocument',
            options={'ordering': ['-ingested_at']},
        ),
        migrations.AlterModelOptions(
            name='stockanalysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainedmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
