# Generated by Django 5.1.7 on 2026-07-31 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('MF', 'Mutual Fund'), ('GOLD', 'Gold'), ('REIT', 'REIT'), ('BOND', 'Bond')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('qty', models.FloatField(default=0)),
                ('avg_price', models.FloatField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
