# Generated by Django 5.1.7 on 2026-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetholding',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
