# Generated by Django 5.1.7 on 2026-07-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetholding',
            options={'ordering': ['-added_at']},
        ),
    ]
