# Generated by Django 5.1.7 on 2026-08-05 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenticWorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('risk_score', models.CharField(max_length=20)),
                ('confidence', models.CharField(max_length=20)),
                ('expected_return', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
