# Generated by Django 5.1.7 on 2026-07-31 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('MF', 'Mutual Fund'), ('GOLD', 'Gold & SGB'), ('REIT', 'REIT')], max_length=10)),
                ('symbol', models.CharField(help_text='Yahoo Finance Ticker (e.g. MON100.NS)', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short Display Code (e.g. PP, SGB)', max_length=10)),
                ('qty', models.FloatField(default=0.0)),
                ('avg_price', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(choices=[('ANGELONE', 'Angel One'), ('ZERODHA', 'Zerodha Kite'), ('UPSTOX', 'Upstox')], default='ANGELONE', max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=50, null=True)),
                ('totp_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investwise.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(db_index=True, help_text='FRED series ID (e.g., GDP, CPIAUCSL, FEDFUNDS, DGS10)', max_length=50)),
                ('indicator_name', models.CharField(blank=True, help_text='Human-readable indicator name', max_length=200)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('source', models.CharField(choices=[('FRED', 'Federal Reserve Economic Data'), ('WORLDBANK', 'World Bank Open Data')], default='FRED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['indicator_code', '-date'], name='investwise__indicat_cc3686_idx')],
                'unique_together': {('indicator_code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SEC_10K', 'SEC 10-K Annual Report'), ('SEC_10Q', 'SEC 10-Q Quarterly Report'), ('SEC_8K', 'SEC 8-K Current Report'), ('EARNINGS', 'Earnings Call Transcript'), ('NEWS', 'News Article'), ('RESEARCH', 'Research Report')], max_length=20)),
                ('stock_symbol', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, help_text='Date of the original filing/publication', null=True)),
                ('chroma_collection', models.CharField(help_text='ChromaDB collection name where chunks are stored', max_length=100)),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of text chunks created from this document')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ingested_at'],
                'indexes': [models.Index(fields=['stock_symbol', 'source_type'], name='investwise__stock_s_bcd417_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=20)),
                ('stock_name', models.CharField(blank=True, max_length=200)),
                ('time_horizon', models.CharField(choices=[('SHORT', 'Short-Term (1-30 days)'), ('LONG', 'Long-Term (3-12+ months)')], max_length=10)),
                ('investment_score', models.FloatField(help_text='Final 0-100 score from XGBoost Decision Cluster')),
                ('confidence', models.FloatField(help_text='Model confidence as a probability (0.0-1.0)')),
                ('recommendation', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], max_length=20)),
                ('fundamental_score', models.FloatField(blank=True, null=True)),
                ('quant_score', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('fundamental_data', models.JSONField(blank=True, help_text='Full output from Fundamental Analysis Cluster', null=True)),
                ('quant_data', models.JSONField(blank=True, help_text='Full output from Quant & Valuation Cluster (DCF, technicals)', null=True)),
                ('sentiment_data', models.JSONField(blank=True, help_text='Full output from Market Intelligence Cluster (news, macro)', null=True)),
                ('shap_values', models.JSONField(blank=True, help_text='SHAP values array for the XGBoost prediction', null=True)),
                ('top_factors', models.JSONField(blank=True, help_text='Top 10 driving factors: [{name, value, impact}, ...]', null=True)),
                ('nn_model_used', models.CharField(choices=[('LSTM', 'LSTM (Long Short-Term Memory)'), ('GRU', 'GRU (Gated Recurrent Unit)'), ('FNN', 'FNN (Feedforward Neural Network)'), ('ENSEMBLE', 'Ensemble (Multiple Models)')], help_text='Which NN architecture was routed based on time horizon', max_length=10)),
                ('predicted_price', models.FloatField(blank=True, help_text="Neural network's price prediction for the target horizon", null=True)),
                ('current_price', models.FloatField(blank=True, help_text='Current market price at time of analysis', null=True)),
                ('prediction_horizon_days', models.IntegerField(help_text='Number of days into the future the prediction targets')),
                ('portfolio_suggestion', models.JSONField(blank=True, help_text='Markowitz/Black-Litterman optimal allocation suggestion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Total wall-clock time for the full analysis pipeline', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('BUY_AGREE', 'Agreed with Buy'), ('HOLD_AGREE', 'Agreed with Hold'), ('SELL_AGREE', 'Agreed with Sell'), ('REJECT', 'Rejected Recommendation')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optional user comment explaining their feedback')),
                ('actual_outcome', models.FloatField(blank=True, help_text='Actual return % measured after the prediction horizon', null=True)),
                ('outcome_measured_at', models.DateTimeField(blank=True, null=True)),
                ('reward_signal', models.FloatField(blank=True, help_text='Computed reward value for the RLHF model: +1.0 (correct agree), -1.0 (incorrect agree), +0.5 (correct reject), -0.5 (incorrect reject)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='investwise.stockanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('LSTM', 'LSTM (Long Short-Term Memory)'), ('GRU', 'GRU (Gated Recurrent Unit)'), ('FNN', 'FNN (Feedforward Neural Network)'), ('XGBOOST', 'XGBoost Gradient Boosting'), ('CATBOOST', 'CatBoost Gradient Boosting'), ('REWARD', 'RLHF Reward Model')], max_length=20)),
                ('stock_symbol', models.CharField(blank=True, help_text='Null = general-purpose model (not stock-specific)', max_length=20, null=True)),
                ('version', models.IntegerField(default=1)),
                ('file_path', models.CharField(help_text='Absolute path to the serialized model file', max_length=500)),
                ('metrics', models.JSONField(help_text='Training/validation metrics: {rmse, mae, r2, accuracy, ...}')),
                ('training_samples', models.IntegerField(blank=True, help_text='Number of training samples used', null=True)),
                ('feature_count', models.IntegerField(blank=True, help_text='Number of input features', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active model per (model_type, stock_symbol)')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('training_duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['model_type', 'stock_symbol', 'is_active'], name='investwise__model_t_ca6cca_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks_units', models.FloatField(default=0.0)),
                ('mf_units', models.FloatField(default=0.0)),
                ('gold_units', models.FloatField(default=0.0)),
                ('reits_units', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('full_analysis', 'Full Stock Analysis'), ('fundamental_only', 'Fundamental Analysis Only'), ('sentiment_only', 'Sentiment Analysis Only'), ('portfolio_optimize', 'Portfolio Optimization'), ('retrain_model', 'Model Retraining'), ('ingest_filing', 'SEC Filing Ingestion')], max_length=50)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery async result ID for task management', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('input_data', models.JSONField(help_text='Task input parameters: {symbol, time_horizon, ...}')),
                ('result_data', models.JSONField(blank=True, help_text='Task output (analysis_id, scores, etc.)', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('current_step', models.CharField(blank=True, default='', help_text='Current processing step for real-time UI updates', max_length=100)),
                ('progress_percent', models.IntegerField(default=0, help_text='Completion percentage (0-100) for progress bar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='investwise__user_id_36bd1a_idx'), models.Index(fields=['celery_task_id'], name='investwise__celery__748041_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['stock_symbol', '-created_at'], name='investwise__stock_s_fcce41_idx'),
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['user', '-created_at'], name='investwise__user_id_1cf025_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentfeedback',
            index=models.Index(fields=['analysis', 'feedback_type'], name='investwise__analysi_0b92cd_idx'),
        ),
    ]
