# Generated by Django 6.0.7 on 2026-07-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investwise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brokercredentials',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brokercredentials',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brokercredentials',
            name='pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brokercredentials',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
