# Generated by Django 6.0.7 on 2026-07-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investwise', '0002_brokercredentials_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercredentials',
            name='broker_name',
            field=models.CharField(choices=[('ANGELONE', 'Angel One'), ('ZERODHA', 'Zerodha Kite'), ('UPSTOX', 'Upstox')], default='ANGELONE', max_length=50),
        ),
    ]
