# Generated by Django 6.0.7 on 2026-07-26 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investwise', '0003_brokercredentials_broker_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('MF', 'Mutual Fund'), ('GOLD', 'Gold & SGB'), ('REIT', 'REIT')], max_length=10)),
                ('symbol', models.CharField(help_text='Yahoo Finance Ticker (e.g. MON100.NS)', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short Display Code (e.g. PP, SGB)', max_length=10)),
                ('qty', models.FloatField(default=0.0)),
                ('avg_price', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
