# Generated by Django 6.0.7 on 2026-07-26 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investwise', '0006_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
