# Generated by Django 5.1.7 on 2026-07-31 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(choices=[('ANGELONE', 'Angel One'), ('ZERODHA', 'Zerodha')], default='ANGELONE', max_length=20)),
                ('_api_key', models.CharField(blank=True, db_column='api_key', default='', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=100)),
                ('_pin', models.CharField(blank=True, db_column='pin', default='', max_length=255)),
                ('_totp_secret', models.CharField(blank=True, db_column='totp_secret', default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('xirr', models.FloatField(default=0.0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
